[local]
localhost

[mongodb]
mongodb-dev.roboshop.online

[catalogue]
catalogue-dev.roboshop.online

[redis]
redis-dev.roboshop.online

[user]
user-dev.roboshop.online

[cart]
cart-dev.roboshop.online

[mysql]
mysql-dev.roboshop.online

[shipping]
shipping-dev.roboshop.online

[rabbitmq]
rabbitmq-dev.roboshop.online

[payment]
payment-dev.roboshop.online

[frontend]
frontend-dev.roboshop.online
